hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000    
spring.zipkin.base-url: http://localhost:9411/
spring.sleuth.sampler.probability: 1
spring.boot.admin.url: http://localhost:8095
management.security.enabled: false
spring:
  application:
    name: gateway-service
  boot:
    admin:
      client:
        url: http://localhost:8095
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: inventory-service
        uri: lb://inventory-service
        predicates:
        - Path=/inventory/**
      - id: pricing-service
        uri: lb://pricing-service
        predicates:
        - Path=/price/**
management:
  endpoints:
    web:
      exposure:
        include: "*"     

server:
  port: 8887

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true